# Generated by Django 4.1.7 on 2023-04-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_register_phone_alter_register_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='gloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('reqamount', models.IntegerField()),
                ('annualincome', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
