# Generated by Django 4.1.7 on 2023-04-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_gloan_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gloan',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='gloan',
            old_name='lastname',
            new_name='lname',
        ),
        migrations.AlterField(
            model_name='gloan',
            name='dob',
            field=models.CharField(max_length=10),
        ),
    ]
