# Generated by Django 4.1.7 on 2023-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_gloan_goldloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('reqamount', models.IntegerField()),
                ('annualincome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('reqamount', models.IntegerField()),
                ('annualincome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('reqamount', models.IntegerField()),
                ('annualincome', models.IntegerField()),
            ],
        ),
    ]
