# Generated by Django 4.2 on 2023-05-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_uploaded_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_documents',
            old_name='loantype',
            new_name='type',
        ),
    ]
